name: Deploy MkDocs Site to GitHub Pages
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: |
          python -m pip install --upgrade pip  # Upgrades pip
          pip install -r requirements.txt      # Installs dependencies from requirements.txt
      - run: mkdocs gh-deploy --force
